name: ItenMart
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  # sdk: '>=3.0.5 <4.0.0'
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  firebase_storage: ^11.4.1
  cloud_firestore: ^4.12.2
  # firebase_core: ^1.24.0
  # firebase_auth: ^3.11.2
  # firebase_storage: ^10.3.11
  # cloud_firestore: ^3.5.1
  flutter:
    sdk: flutter
  get: ^4.6.5
  image_picker: ^0.8.6
  mobile_scanner: ^2.1.0
  velocity_x: ^3.5.1
  math_expressions: ^2.3.1
  font_awesome_flutter: ^9.1.0
  sqflite: ^2.3.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  recase: ^4.1.0
  flutter_dotenv: ^5.0.2
  bloc: ^8.1.0

  # Flutter window webview
  webview_windows: ^0.2.2
  # Barcode scanner for android and ios
  flutter_barcode_scanner: ^2.0.0
  #Get assets path for window platform
  path: ^1.8.2
  #checking permissions
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: sans_regular
      fonts:
        - asset: assets/fonts/sans_regular.ttf

    - family: sans_semibold
      fonts:
        - asset: assets/fonts/sans_semibold.ttf

    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf
